### ISSUE TITLE
allowed_vlan typo

### ISSUE THREAD

**Issue by kiksen** [arezazadeh/cisco_config_parser#18]
Hello,
I think there is an "s" missing somewhere.

I'm parsing:

interface TenGigabitEthernet1/0/7
 description Uplink1
 switchport trunk allowed vlan 30,40,50
 switchport mode trunk
 source template Access
 service-policy output QUEUE-OUT_

get_l2_trunk_interfaces returns the following dict:

{'name': 'TenGigabitEthernet1/0/7', 'description': 'Uplink1', **'allowed_vlans': None**, 'dhcp_snooping': None, 'dhcp_relay': None, 'voice_vlan': None, 'state': None, 'spanning_tree': None, 'native_vlan': None, 'children': ['description Uplink1', 'switchport trunk allowed vlan 30,40,50', 'switchport mode trunk', 'source template Access', 'service-policy output QUEUE-OUT'], **'allowed_vlan': '30,40,50'**}

there is one allowed_vlan and allowed_vlans. Probably only allowed_vlans is needed.

Thank you!
Regards

**Comment by arezazadeh** [comment]
Thank you i will look into this

**Comment by arezazadeh** [comment]
@kiksen  this is fixed in 2.2.6 Thanks for reporting it

**Comment by kiksen** [comment]
Thank you!
