### ISSUE TITLE
Support IPv6 addresses

### ISSUE THREAD

**Issue by kevinkrk-slac** [arezazadeh/cisco_config_parser#22]
Add support for IPv6 addresses in L3 interface parsing & objects.

**Comment by kevinkrk-slac** [comment]
For example:
`interface Vlan1432`
` ip address 134.79.102.2 255.255.255.192`
` ipv6 address 2620:114:D000:2598::1/64`

**Comment by arezazadeh** [comment]
sure i will work on it for the next release. thanks for the suggestion.

**Comment by arezazadeh** [comment]
ipv6 added to 2.3.0
